// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"/dashboard","name":"dashboard","icon":"smile","parentId":"ant-design-pro-layout","id":"1"},"2":{"path":"/dashboard","redirect":"/dashboard/home","parentId":"1","id":"2"},"3":{"name":"analysis","path":"/dashboard/home","parentId":"1","id":"3"},"4":{"name":"dataflow","path":"/dashboard/dataflow","parentId":"1","id":"4"},"5":{"name":"adsflow","path":"/dashboard/adsflow","parentId":"1","id":"5"},"6":{"name":"userflow","path":"/dashboard/userflow","parentId":"1","id":"6"},"7":{"path":"/user","layout":false,"id":"7"},"8":{"name":"login","path":"/user/login","parentId":"7","id":"8"},"9":{"path":"/admin","name":"admin","icon":"crown","access":"canAdmin","parentId":"ant-design-pro-layout","id":"9"},"10":{"path":"/admin","redirect":"/admin/sub-page","parentId":"9","id":"10"},"11":{"path":"/admin/sub-page","name":"sub-page","parentId":"9","id":"11"},"12":{"path":"/","redirect":"/dashboard","parentId":"ant-design-pro-layout","id":"12"},"13":{"path":"*","layout":false,"id":"13"},"ant-design-pro-layout":{"id":"ant-design-pro-layout","path":"/","isLayout":true},"umi/plugin/openapi":{"path":"/umi/plugin/openapi","id":"umi/plugin/openapi"}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import('./EmptyRoute')),
'2': React.lazy(() => import('./EmptyRoute')),
'3': React.lazy(() => import(/* webpackChunkName: "p__dashboard__home__index" */'@/pages/dashboard/home/index.tsx')),
'4': React.lazy(() => import(/* webpackChunkName: "p__dashboard__dataflow__index" */'@/pages/dashboard/dataflow/index.tsx')),
'5': React.lazy(() => import(/* webpackChunkName: "p__dashboard__adsflow__index" */'@/pages/dashboard/adsflow/index.tsx')),
'6': React.lazy(() => import(/* webpackChunkName: "p__dashboard__userflow__index" */'@/pages/dashboard/userflow/index.tsx')),
'7': React.lazy(() => import('./EmptyRoute')),
'8': React.lazy(() => import(/* webpackChunkName: "p__User__Login__index" */'@/pages/User/Login/index.tsx')),
'9': React.lazy(() => import('./EmptyRoute')),
'10': React.lazy(() => import('./EmptyRoute')),
'11': React.lazy(() => import(/* webpackChunkName: "p__Admin" */'@/pages/Admin.tsx')),
'12': React.lazy(() => import('./EmptyRoute')),
'13': React.lazy(() => import(/* webpackChunkName: "p__404" */'@/pages/404.tsx')),
'ant-design-pro-layout': React.lazy(() => import(/* webpackChunkName: "umi__plugin-layout__Layout" */'/Users/mac/Downloads/react/p2/adminend/baise/src/.umi/plugin-layout/Layout.tsx')),
'umi/plugin/openapi': React.lazy(() => import(/* webpackChunkName: "umi__plugin-openapi__openapi" */'/Users/mac/Downloads/react/p2/adminend/baise/src/.umi/plugin-openapi/openapi.tsx')),
},
  };
}
