// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import SmileOutlined from '/Users/mac/Downloads/react/p2/adminend/baise/node_modules/@ant-design/icons/es/icons/SmileOutlined';
import CrownOutlined from '/Users/mac/Downloads/react/p2/adminend/baise/node_modules/@ant-design/icons/es/icons/CrownOutlined';
export default { SmileOutlined, CrownOutlined };
